# Generated by Django 4.1.7 on 2023-02-26 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Analyte",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("analyte_name", models.CharField(blank=True, max_length=64)),
                ("cas", models.CharField(blank=True, max_length=64)),
                ("mdl_cal_spike", models.FloatField()),
                ("mdl_cal_blank", models.FloatField()),
                ("mdl_verified", models.FloatField()),
                ("current_mdl", models.FloatField()),
                ("current_rl", models.FloatField()),
                ("units", models.CharField(blank=True, max_length=64)),
            ],
        ),
    ]
