# Generated by Django 4.1.7 on 2023-03-01 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calculate", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="data",
            name="collect_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="data",
            name="prep_run_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="data",
            name="receive_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="data",
            name="run_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
