# Generated by Django 4.1.7 on 2023-03-01 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calculate", "0004_alter_data_collect_date_alter_data_prep_run_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="data",
            name="prep_run_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="data",
            name="receive_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="data",
            name="run_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
